### ISSUE TITLE
you literally just copied someone elses work

### ISSUE THREAD

**Issue by Jrepxc** [piggydoe/Xulu-Src-Deobf#1]
what was the point of this

**Comment by piggydoe** [comment]
yes its true i copied someone else's work, all you have to do is run it through a deobfuscator its very simple but since there is more it will spread more awareness for xulu's src code, im not taking any credit for this or claiming it as my own its simply to spread the src code

**Comment by piggydoe** [comment]
336 the person ok-ed this as long as i have credit to him, which i do
